### ISSUE TITLE
Redundant line of sass need removing

### ISSUE THREAD

**Issue by mdwragg** [PredixDev/px-normalize-design#1]
Hi Kate,

Given:

https://github.com/PredixDev/px-normalize-design/commit/667b179788fb85120cff1e061f38c79f8d8a2bb2

This line is now redundant and should be removed. Please remove and retest. Thanks

https://github.com/PredixDev/px-normalize-design/blob/master/_generic.normalize.scss#L22

Thanks,
M.

**Comment by katemenkhaus** [comment]
Fixed in prerelease.
